//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAlpha.Models
{
    using PropertyChanged;
    using System;    
    using System.Collections.Generic;
    [AddINotifyPropertyChangedInterface]
    public partial class user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string pswd { get; set; }
    }
}
