//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAlpha.Models
{
    using PropertyChanged;
    using System;
    using System.Collections.Generic;
    [AddINotifyPropertyChangedInterface]
    public partial class view_show_providers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string social_name { get; set; }
        public string cnpj { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string main_activity { get; set; }
        public bool active { get; set; }
    }
}
